### ISSUE TITLE
actions in issues show "no URL"

### ISSUE THREAD

**Issue by aschmidt74** [berti92/mega_calendar#100]
- when I install the plugin `no url` is displayed for every subtask `...` action on issue pages:
![snap_redmine](https://user-images.githubusercontent.com/45806825/146663727-2b5bbb79-44b8-4cc7-99e1-ca211d7f5df9.PNG)
- when I remove the `mega_calendar` plugin, actions are usable again,
- actions in the issues/list view are not affected and work as expected.

**Comment by berti92** [comment]
Can't reproduce this with redmine 5.1.X
