### ISSUE TITLE
rake aborts on redmine 5.0: cannot load such file mega_calendar/filters.rb

### ISSUE THREAD

**Issue by teatower** [berti92/mega_calendar#104]
Hello to you :-)
are you still maintaining this plugin actively?

Upgrading to redmine 5 `bundle exec rake redmine:plugins:migrate RAILS_ENV=procution` breaks with error
`rake aborted!
LoadError: cannot load such file -- mega_calendar/filters.rb
`
Thank you!

**Comment by berti92** [comment]
I'm sorry this plugin - as for now - is only compatible with Redmine 4.X
I already tried to migrate this plugin to version 5.x, but this takes a lot of work.

I can't tell when this plugin is available for the current redmine version.

**Comment by teatower** [comment]
I know it is hard work to mantain a plugin and can fully understand. Sorry, anyway, I would have loved to get it installed. Thank you very much for getting back to me!

**Comment by berti92** [comment]
Fixed in the current version (v1.9.0)
