### ISSUE TITLE
No issue show up if start or due date empty

### ISSUE THREAD

**Issue by channdy** [berti92/mega_calendar#105]
I have some problem with the issue that are not using the standard date fields such as start date or due date. So in this case I did not see those issues show up on calenda. Is it possible to use created date instead? Thanks

Edit: I got a workaround for this problem. I have to add start date field to the project and set it to auto fill with current date

**Comment by berti92** [comment]
Hmmm... seems to be a very specific setup. I'm glad that you found a workaround.
