### ISSUE TITLE
TicketTimeController not defined

### ISSUE THREAD

**Issue by albenik85** [berti92/mega_calendar#106]
I am trying to run this plugin within our redmine 5.0.2 installation. After installing the plugin redmine doesn't work at all anymore. Error message in the logfile of the webserver is:
[ E 2022-08-12 15:24:46.4786 40937/Tf age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /opt/redmine: The application encountered the following error: expected file /opt/redmine/plugins/mega_calendar/app/controllers/ticket_time_controller.rb to define constant TicketTimeController, but didn't (Zeitwerk::NameError)

The file ticket_time_controller.rb is empty but I don't know what is expected from this file.
Any ideas what could be wrong here?

**Comment by berti92** [comment]
Could you remove the file /opt/redmine/plugins/mega_calendar/app/controllers/ticket_time_controller.rb and restart your redmine? If it works then please tell me, because then I have to delete the file from the repository :) Thanks in advance!

**Comment by albenik85** [comment]
Tried it, the error message is different now:

Could not spawn process for application /opt/redmine: The application encountered the following error: uninitialized constant MegaCalendar::Filters (NameError)

**Comment by albenik85** [comment]
It seems like the issue just occurs in production environment. I tried to verify it on a development environment using the same versions and it is working there. Are you able to run it using the production Rails environment?

**Comment by berti92** [comment]
Great, that was the info which helped me. I fixed the bug in version v1.9.1
