### ISSUE TITLE
Calendar doesn't show all tickets

### ISSUE THREAD

**Issue by albenik85** [berti92/mega_calendar#107]
For me the calendar shows just tickets I am assigned to:
- I can't see the ones where I was selected as additional assignee
- "All tickets" doesn't show anything else than what I can already see with having "My tickets" enabled 

Is it a bug or a configuration issue?

**Comment by berti92** [comment]
Could you send me a list of your used plugins in Redmine? Thank you!

**Comment by albenik85** [comment]
Here is the list of my plugins:
mega_calendar
redmine_add_absolute_time
redmine_agile
redmine_budgets
redmine_checklists
redmine_contacts
redmine_contacts_helpdesk
redmine_contacts_invoices
redminecrm
redmine_crm_mailchimp
redmine_dmsf
redmine_drawio
redmine_finance
redmine_issue_dynamic_edit
redmine_people
redmine_products
redmine_questions
redmine_recurring_tasks
redmine_reporter
redmine_resources
redmineup_tags
redmine_wktime
redmine_x_assets
redmine_x_client
redmine_x_gantt
redmine_zenedit

**Comment by berti92** [comment]
Sorry for my late response "additional assignee" is not a redmine core function and therefore this plugin is not compatible with this field.
