### ISSUE TITLE
Replace vpim gem

### ISSUE THREAD

**Issue by berti92** [berti92/mega_calendar#110]
Because of vpim this plugin doesn't work with ruby 3.X

**Comment by hwiorn** [comment]
vPIM is updated their Github. But the gem is not released since 2013.  
The enumerator fix for Ruby 2.7+ is already patched last year in the repo.

```ruby
#gem "vpim", "13.11.11"
gem "vpim", :git => "https://github.com/ahorek/vpim.git", :ref => "b33ec0e9cee9899331ebc5838c69d622fcbe6970" # Latest enumerator fix for Ruby 2.7+
```

I confirmed it works with redmine 5.1.1 and ruby 3.2.

**Comment by berti92** [comment]
Thank you, I used your snippet and updated the gemfile

**Comment by Saylrman64** [comment]
Hello,

I too tried to install this but get an error:

# bundle install
Fetching https://github.com/ahorek/vpim.git
fatal: Could not parse object 'b33ec0e9cee9899331ebc5838c69d622fcbe6970'.
Git error: command `git reset --hard b33ec0e9cee9899331ebc5838c69d622fcbe6970` in directory
/var/lib/gems/3.0.0/bundler/gems/vpim-b33ec0e9cee9 has failed.
Revision b33ec0e9cee9899331ebc5838c69d622fcbe6970 does not exist in the repository https://github.com/ahorek/vpim.git. Maybe you misspelled it?
If this error persists you could try removing the cache directory '/var/lib/gems/3.0.0/bundler/gems/vpim-b33ec0e9cee9'

I pulled latest bundle using: #git clone https://github.com/berti92/mega_calendar.git

Am I missing something?

Thanks

**Comment by hwiorn** [comment]
Ugh... `https://github.com/sam-github/vpim.git` is right. The other one's fork version for fixing enumerator. It's not main repository.  So you have to use like below.

```
#gem "vpim", "13.11.11"
gem "vpim", :git => "https://github.com/sam-github/vpim.git", :ref => "b33ec0e9cee9899331ebc5838c69d622fcbe6970" # Latest enumerator fix for Ruby 2.7+
```

@berti92 Sorry for this confusion. I think it needs to be changed the repo.

**Comment by Saylrman64** [comment]
Thank you.
That repo does work.

And thank you for the quick response.

**Comment by berti92** [comment]
I updated it again, thank you.

**Comment by davidjharder** [comment]
Sorry for what may be a dumb question: Does this mean mega calendar can now be used on redmine with Ruby 3.x?

**Comment by Saylrman64** [comment]
FWIW, I just loaded it on Redmine 5.0.7

Environment:
  Redmine version                5.0.7.stable.22485
  Ruby version                   3.0.2-p107 (2021-07-07) [x86_64-linux-gnu]
  Rails version                  6.1.7.6
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Default

**Comment by hwiorn** [comment]
> Sorry for what may be a dumb question: Does this mean mega calendar can now be used on redmine with Ruby 3.x?

Yes, as I already said it. It works on ruby 3.2 and redmine 5.1.1.
