### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by Nixan04** [berti92/mega_calendar#111]
ubuntu@ip-10-0-11-241:/var/www/pms.ivldsp.com/plugins$ bundle exec rake redmine:plugins NAME=mega_calendar-master  RAILS_ENV=production
(in /var/www/pms.ivldsp.com)
rake aborted!
LoadError: cannot load such file -- enumerator
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `block in require'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
/var/lib/gems/2.7.0/gems/vpim-13.11.11/lib/vpim/property/recurrence.rb:10:in `<top (required)>'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `block in require'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
/var/lib/gems/2.7.0/gems/vpim-13.11.11/lib/vpim/vevent.rb:20:in `<top (required)>'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `block in require'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
/var/lib/gems/2.7.0/gems/vpim-13.11.11/lib/vpim/icalendar.rb:15:in `<top (required)>'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `block in require'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
/var/lib/gems/2.7.0/gems/vpim-13.11.11/lib/vpim.rb:12:in `<top (required)>'
/var/lib/gems/2.7.0/gems/bundler-2.4.1/lib/bundler/runtime.rb:60:in `require'
/var/lib/gems/2.7.0/gems/bundler-2.4.1/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/var/lib/gems/2.7.0/gems/bundler-2.4.1/lib/bundler/runtime.rb:55:in `each'
/var/lib/gems/2.7.0/gems/bundler-2.4.1/lib/bundler/runtime.rb:55:in `block in require'
/var/lib/gems/2.7.0/gems/bundler-2.4.1/lib/bundler/runtime.rb:44:in `each'
/var/lib/gems/2.7.0/gems/bundler-2.4.1/lib/bundler/runtime.rb:44:in `require'
/var/lib/gems/2.7.0/gems/bundler-2.4.1/lib/bundler.rb:195:in `require'
/var/www/pms.ivldsp.com/config/application.rb:18:in `<top (required)>'

**Comment by berti92** [comment]
I think you're using Ruby 3.X. This plugin is currently only compatible with Ruby 2.x
