### ISSUE TITLE
How can I set holiday for all users?

### ISSUE THREAD

**Issue by riggy2013** [berti92/mega_calendar#114]
I want to set public holiday to all, how can I do it?

Thanks,
David

**Comment by riggy2013** [comment]
This plugin will not update the task end_date per holiday setting, right?

I tried to set holiday to one user, but the task end_date didn't change.

**Comment by riggy2013** [comment]
Say, a task is from Jan 1 to Jan 5 originally. If I set Jan 4 as public holiday, it should shift one day that it is now from Jan 1 to Jan 6, treating holiday as non-working days just as Saturday and Sunday.

**Comment by berti92** [comment]
Ah, now I understand. You're right, this function isn't implemented and not planned to be implemented. Holidays are just a reserved slot in the calendar, without any constraints for other events.
