### ISSUE TITLE
Feature request: Option to change the text color in the calendar

### ISSUE THREAD

**Issue by peipert** [berti92/mega_calendar#117]
After upgrading the mega calendar from version 1.8.1 (with redmine 4.2.10) to 1.9.5 (with redmine 5.0.8) and later 1.9.6 with (redmine 5.1.2) it was hard to read the text in the calendar because the text color changed from black to white.

We rolled this back for us by changing 
"--fc-event-text-color:#fff;" into "--fc-event-text-color:#000;"
in the files
mega_calendar/assets/javascripts/fullcalendar-6.1.9/dist/index.global.min.js
and
mega_calendar/assets/javascripts/fullcalendar-6.1.9/dist/index.global.js

It would be great to have an option to change this color in the configuration.

**Comment by peipert** [comment]
Hello Berti92,
after upgrading the plugin with the 1.9.8 release, the shown version number is 1.9.7 and there ist no option for the text color.
Could you please check this?
Thanks in advance
Peter

**Comment by berti92** [comment]
Sorry, my bad. https://github.com/berti92/mega_calendar/releases/tag/1.9.8bugfix Now it should work.

**Comment by peipert** [comment]
Great, now it works. 

Two little things, that are not critical but could improve the plugin:
1. The default text color could be black. 
2. After opening the configuration page of the plugin the color chooser is open and the fields for the different colors are hidden behind it. You have to click somewhere on the page to hide the color chooser. This is not intuitive and one may not find the different options.

Thanks again for the new Version.
Peter
