### ISSUE TITLE
Displayed users and groups

### ISSUE THREAD

**Issue by mael-chouteau** [berti92/mega_calendar#118]
Hi, I've just migrated from Redmine 3 to 5 and during the installation of this plugin I noticed that the way that we can select the users and groups to display in the calendar changed since #98.

Before that, we just selected the groups and every user of that group was shown. Now every time a new employee comes in, we have to re select everyone in the company while holding CTRL to add just one person. 

This is just not feasible as in the list we have hundreds of names. I'm going to fork the project to make changes for our use case.

I think that giving back the old menu is a good idea, while keeping the display of groups issues in the calendar as well as every user of that group. Maybe I can add a button to only show groups issues if the group mode is selected.

I don't understand why this was removed.

**Comment by berti92** [comment]
I guess you fixed it with your last PR? -> Closed

**Comment by mael-chouteau** [comment]
No, this is a different issue, the last PR was just a cosmetic fix to the filter panel.

**Comment by berti92** [comment]
> I'm going to fork the project to make changes for our use case.

Great, I'll merge the changes then. Thank you!
-> CLOSED
