### ISSUE TITLE
Calendar export requires login

### ISSUE THREAD

**Issue by JiriValasek** [berti92/mega_calendar#123]
Hi, 

I installed the plugin today in version 1.5.0 (redmine 5.1.2) and I'm facing an issue regarding export.

I need to import the calendar into ms365 exchange calendars via "subscribe from web". But when I'm using the URL from the wiki Thunderbird guide, it requires login (redirects).

Is there a way how to avoid that so it can be imported into ms365 / Google calendar? 

Thanks for any help or directions 🙂

**Comment by berti92** [comment]
If you setup an api key and enable the rest api, then it should be possible to export the issues.
https://github.com/berti92/mega_calendar/wiki/Setup-sync-in-Thunderbird

**Comment by JiriValasek** [comment]
It is, but only when you are also logged in. Microsoft exchange has no way to login, which is the issue. 

For one time expert after login it's just fine, but I need automatic updates for my use case.
