### ISSUE TITLE
Some bugs?

### ISSUE THREAD

**Issue by weSh** [berti92/mega_calendar#13]
When I create an Issue and select a tracker, I lose Start and End choices...
I did the change you describe in https://github.com/berti92/mega_calendar/commit/bbb3af04ebedb741cfc5a017ae3f8f049e856118 but it's not working.

Another bug: when you are in Holidays tab and you click on New, the link is not using the good path.
For example, my serv is running on https://x.x.x.x/redmine
When I click on New, the used path is : https://x.x.x.x/holidays/new

**Comment by berti92** [comment]
When I create an Issue and select a tracker, I lose Start and End choices...
I did the change you describe in bbb3af0 but it's not working.
-> Can't reproduce, did you restarted the server ?

Another bug: when you are in Holidays tab and you click on New, the link is not using the good path.
For example, my serv is running on https://x.x.x.x/redmine
When I click on New, the used path is : https://x.x.x.x/holidays/new
-> Fixed please define the subpath at the plugin settings
-> In your case type in "/redmine/" without dbl quotes
