### ISSUE TITLE
Sync with google calendar or iCal

### ISSUE THREAD

**Issue by riccardonar** [berti92/mega_calendar#20]
I'm interested in this plugin and would be perfect to integrate it with google calendar.
Another plugin already does this: https://github.com/MYchaieb/redmine_gc_sync

This is my issue MYchaieb/redmine_gc_sync#2 to @MYchaieb

**Comment by riccardonar** [comment]
I've done this plugin: https://github.com/riccardonar/mega_calendar_gc_sync
It can be better and i hope that for you can be interesting

**Comment by berti92** [comment]
Thank you very much for your work!
