### ISSUE TITLE
Add times to available columns in issues

### ISSUE THREAD

**Issue by berti92** [berti92/mega_calendar#24]
Times should be visible in issues list + export.

Thanks to @lkehositse  for this nice idea.

**Comment by riccardonar** [comment]
I think that the best solution is to use custom field to manage time, so anybody will decide by himself and, very very important, custom fields are supported and can be managed in smartphone app.

**Comment by berti92** [comment]
Very good point :) I'll keep that in mind

**Comment by lkehositse** [comment]
Hi

Thanks for attending to some of the issues I raised with you. Listen - will you be able to pull off this "enhancement"?
I need to be able to include "end time" in my monthly reports.

Please advise.

Thanks again.

**Comment by berti92** [comment]
Sure I think it should be finished next week 

Greetings Berti

**Comment by berti92** [comment]
Hi,
the export or list view is not so easy to implement, so I can't fix this within this week.

I will make this with all changes in Version 2, but this takes some time.

Sorry, please be patient.

**Comment by lkehositse** [comment]
Hi

I hear you, best we wait for your next version then. But when is version 2
release date?

Thanks a mil for your efforts.

Regards
lesego Kehositse

Regards
Lesego Kehositse
078 357 2732 | 083 570 2782

**Comment by berti92** [comment]
Version 2 will be a big step for this plugin and much work must be done, so there is no release date.

**Comment by berti92** [comment]
Closed, because no time to enhance this plug any further.
