### ISSUE TITLE
Support for Redmine 3.2.2

### ISSUE THREAD

**Issue by amityk77** [berti92/mega_calendar#29]
Hello,

Please can you tell, when this will be available for Redmine v3.2.2, though it gets installed, but does not work as expected.

**Comment by berti92** [comment]
Hi,

I will start the work in the next month.

**Comment by berti92** [comment]
Done

**Comment by amityk77** [comment]
hello again,

thanks for implementing the same on 3.2.2, It works and calendar is now visible. :)
(only I had to deal with sub-path, as no detail info was available) :(

There are few suggestions, which I would like to mention:
1) Options for Setting Global holidays, currently it is not working.
2) We have Default holidays on Saturdays and Sundays, so option to set the same globally should be available.
3) "Calendar" and "Holiday" are visible in Main Menu., which I think should be administrative option.

**Comment by archonwang** [comment]
could it support redmine 3.3? Thanks.

**Comment by berti92** [comment]
Hi, 
I'm currently working on the 3.3 support

Greetings Berti
