### ISSUE TITLE
Redmine on sub path

### ISSUE THREAD

**Issue by duyluonglc** [berti92/mega_calendar#3]
This is an useful plugin but i have broblems:
My redmine url: http://mydomain.com/redmine
- css and js files can not be loaded.
- http://mydomain.com/redmine/holidays 
=> click "new" refer to http://mydomain.com/holidays/new
result: page not found ^^

**Comment by berti92** [comment]
Hi, thanks for your response. I'm sorry, i can't reproduce your problem. My redmine goes over Passenger. All works fine. https://www.phusionpassenger.com/library/deploy/apache/deploy/ruby/
Maybe this thread helps you. https://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_on_subdirectory_(sub-URI)_on_Apache
