### ISSUE TITLE
panel blank on Redmine 3.3

### ISSUE THREAD

**Issue by jlibster** [berti92/mega_calendar#30]
This plugin appears to not function at all on redmine 3.3. Installs successfully but panel is blank.

**Comment by berti92** [comment]
Thank you for your feedback.
The calendar itself is on my redmine3.3 installation visible and it works but there are a few other bugs which makes this plugin not so usefull. I'm working on a full 3.3 support.

Have you set the sub-path config correctly?

**Comment by jancybsec** [comment]
I am also having this issue. The Calendar page is entirely blank after my install of the plugin based on the README directions and when i try to create a new holiday it says /holidays/new was not found on this server (shouldn't it be redmine/holidays/new?)
