### ISSUE TITLE
tweaks required...

### ISSUE THREAD

**Issue by amityk77** [berti92/mega_calendar#32]
hello again,

thanks for implementing the same on 3.2.2, It works and calendar is now visible. :-)
(only I had to deal with sub-path, as no detail info was available) :(

There are few suggestions, which I would like to mention:
1) Options for Setting Global holidays, currently it is not working.
2) We have Default holidays on Saturdays and Sundays, so option to set the same globally should be available.
3) "Calendar" and "Holiday" are visible in Main Menu., which I think should be administrative option.
4) When we are into any Project's page, the Calendar displayed in that is still old (default). How to set it up with your new calendar.

**Comment by riccardonar** [comment]
You can try my fork https://github.com/riccardonar/mega_calendar_gc_sync

Il mer 10 ago 2016, 20:11 amityk77 <notifications@github.com> ha scritto:

**Comment by berti92** [comment]
Thank you for your feedback, I will keep it in mind for Version 2

**Comment by berti92** [comment]
Closed, because no time to enhance this plug any further.
