### ISSUE TITLE
Holiday page does not work [SOLVED]

### ISSUE THREAD

**Issue by karlotroiano** [berti92/mega_calendar#36]
Plugin just installed.
Each time I try to open the Holiday page it replies with an internal error.
This is the log:

ActiveRecord::StatementInvalid (Mysql2::Error: Table 'redmine_production.holidays' doesn't exist: SHOW FULL FIELDS FROM `holidays`):
  plugins/mega_calendar/app/controllers/holidays_controller.rb:25:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

[SOLVED] After copying the plugin into [plugin] directory you have to exec: bundle exec rake redmine:plugins:migrate RAILS_ENV=production (more details in www.redmine.org plugin installation how-to)

**Comment by berti92** [comment]
Thank you for your feedback, I updated the README
