### ISSUE TITLE
all tickets as default view

### ISSUE THREAD

**Issue by carepack** [berti92/mega_calendar#39]
first of all,

thank you for the work you're doin'!
Is it possible to have "all tickets" as default view instead of my tickets?

thx

**Comment by berti92** [comment]
If you mean the global calendar, than you can choose "all tickets" and the result is saved in the session this means if you open the calendar the next time then your last choice will be displayed.

**Comment by carepack** [comment]
I noticed that, but any option ta save this for every session? Thx for the respond

**Comment by berti92** [comment]
Sorry this is not planned
