### ISSUE TITLE
Excellent plugin here one request for enhancement!!

### ISSUE THREAD

**Issue by avwifiguy** [berti92/mega_calendar#43]
Hi there,

I am a redmine user for almost 15 yrs now.

recently came across your plugin excellent.

I've been using below simlar plugin.
http://www.redmine.org/plugins/redmine_gc_sync

Your calendar has made few really good things
- added new view and in place editable feature
- added time to the issue
now for me only major issue how can I use this calendar outside of Redmine Web UI. 
- feature missing to get this calendar usable across any device (export calendar) 

I don't have time to look different calendars, so I use a feature in my mobile, web and outlook overlap calendars.  all calendars at one place so I see the conflict. it doesn't matter it should tell me the conflict as these calendars are different but at least I see the view of conflict and I decide. 

I cannot advise what will be the best strategy for you to export this calendar, but I see these options.
- The calendar you are using may have feature to export itself.
- Link this to google calendar or other open source calendars like other plugin doing.

Above these three features will make this calendar as mainstream feature with other enhancements like I see already in your list exportable, project based etc.

Thank you for your time on this Plugin.

Cheers

**Comment by berti92** [comment]
Added export functionality (ics) within V1.4.0
