### ISSUE TITLE
Incompatibillity with local avatars plugin

### ISSUE THREAD

**Issue by DanielBoettner** [berti92/mega_calendar#45]
Hello there,

I would love to test your plugin. Unfortunately there is an issue with a variable and the naming.

See: https://github.com/ncoders/redmine_local_avatars/issues/12

**Comment by acosonic** [comment]
What's the update on this issue?

How can this error be resolved?

**Comment by berti92** [comment]
Actually there is no solution for this issue.

**Comment by acosonic** [comment]
So you think wrapping the plugin's code to module wouldn't help?

**Comment by acosonic** [comment]
;)

**Comment by berti92** [comment]
I didn't know that this problem could be fixed so easy :D

VG Berti
