### ISSUE TITLE
Parent task date relations settings is broken

### ISSUE THREAD

**Issue by janekska** [berti92/mega_calendar#46]
I am using following setting in "Issue tracking" tab:
Parent tasks attributes
Start date / Due date: Independent of subtasks
When I used mega_calendar, that it sets this behavior to kind of Calculated from subtasks and I could not edit parent tast start and end dates, only times (at least fields are editable).

The module I like better than original calendar, but I see there is some "must to have" things:
- permissions at least for roles, but better also per project as module on/off

Sinhronization with google calendar also would be nice - at least in one direction.

Thanks for your module!
If needed I could help with tests.

Brgds

**Comment by berti92** [comment]
Hi,

thank you for your feedback.

The start/due date issue comes from redmine, so it is a bug that the time fields are not greyed out :)

Real permissions comes with V2.

Sync is already given have a look at V1.4.0
