### ISSUE TITLE
the button all issues pemit to show all issues even those of the not public projets

### ISSUE THREAD

**Issue by lhadjadj** [berti92/mega_calendar#47]
Hi, it's me again. 
The All issues button show all issues from all projets even if the projet is not public.
So, a user that do not belong to the projet can show the issue but cannot modify it but he can move the issue to another day. 
Could you restrict the button "all issue" only for one project. So, i user from one projet could show his events and the events from others members of his projet.
Thanks

**Comment by berti92** [comment]
Hi, thank you for your feedback. This feature is already planned to be implemented within v2.

To be honest: V2 will take a long time until it's released, because I got a new job. So currently I find no time to write stuff for this project.

**Comment by lhadjadj** [comment]
Thanks i hope tour new job is cool. I am learning ruby now :)

Envoyé de mon iPad

**Comment by berti92** [comment]
Hey, yes the job is not bad :)

Nice to hear, btw I release at Feb 13th a bigger release of megacalendar.

Best regards 

> Am 07.02.2017 um 20:55 schrieb Laurent HADJADJ <notifications@github.com>:
> 
> Thanks i hope tour new job is cool. I am learning ruby now :)
> 
> Envoyé de mon iPad
>

**Comment by lhadjadj** [comment]
Thank you very very much

Envoyé de mon iPad
