### ISSUE TITLE
Install errors on Redmine 3.3.0

### ISSUE THREAD

**Issue by jlibster** [berti92/mega_calendar#55]
When I try to bundle the plug-in on my redmine 3.3.0 after trying to upgrade from your previous version here is what I get:

 bundle exec rake redmine:plugins:migrate RAILS_ENV=production --trace 
rake aborted!
Child already added
/opt/redmine/redmine-3.3.0/lib/redmine/menu_manager.rb:348:in `add_at'
/opt/redmine/redmine-3.3.0/lib/redmine/menu_manager.rb:365:in `add'
/opt/redmine/redmine-3.3.0/lib/redmine/menu_manager.rb:283:in `push'
/opt/redmine/redmine-3.3.0/lib/redmine/plugin.rb:279:in `menu'
/opt/redmine/redmine-3.3.0/plugins/mega_calendar/init.rb:13:in `block in <top (required)>'
/opt/redmine/redmine-3.3.0/lib/redmine/plugin.rb:75:in `instance_eval'
/opt/redmine/redmine-3.3.0/lib/redmine/plugin.rb:75:in `register'
/opt/redmine/redmine-3.3.0/plugins/mega_calendar/init.rb:4:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/opt/redmine/redmine-3.3.0/lib/redmine/plugin.rb:155:in `block in load'
/opt/redmine/redmine-3.3.0/lib/redmine/plugin.rb:146:in `each'
/opt/redmine/redmine-3.3.0/lib/redmine/plugin.rb:146:in `load'
/opt/redmine/redmine-3.3.0/config/initializers/30-redmine.rb:21:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:652:in `block in load_config_initializer'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:651:in `load_config_initializer'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `each'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `block in <class:Engine>'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
/usr/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
/usr/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `each'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/lib/ruby/2.1.0/tsort.rb:411:in `call'
/usr/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.1.0/tsort.rb:345:in `each'
/usr/lib/ruby/2.1.0/tsort.rb:345:in `call'
/usr/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
/usr/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
/usr/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
/opt/redmine/redmine-3.3.0/config/environment.rb:14:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/opt/redmine/redmine-3.3.0/plugins/a_common_libs/lib/tasks/a_common_libs.rake:1:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/opt/redmine/redmine-3.3.0/lib/tasks/redmine.rake:186:in `block in <top (required)>'
/opt/redmine/redmine-3.3.0/lib/tasks/redmine.rake:186:in `each'
/opt/redmine/redmine-3.3.0/lib/tasks/redmine.rake:186:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:658:in `each'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:658:in `run_tasks_blocks'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/application.rb:452:in `run_tasks_blocks'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:453:in `load_tasks'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `public_send'
/var/lib/gems/2.1.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `method_missing'
/opt/redmine/redmine-3.3.0/Rakefile:7:in `<top (required)>'
/var/lib/gems/2.1.0/gems/rake-11.2.2/lib/rake/rake_module.rb:28:in `load'
/var/lib/gems/2.1.0/gems/rake-11.2.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/var/lib/gems/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:686:in `raw_load_rakefile'
/var/lib/gems/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:96:in `block in load_rakefile'
/var/lib/gems/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/var/lib/gems/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:95:in `load_rakefile'
/var/lib/gems/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:79:in `block in run'
/var/lib/gems/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/var/lib/gems/2.1.0/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
/var/lib/gems/2.1.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'

Please Advise. Thanks!

**Comment by jlibster** [comment]
Okay, I discovered I had to remove the holiday plugin to get this to install, which (if my memory is correct) was required for the previous version. (pre 1x status0

**Comment by berti92** [comment]
Hmmm, if I understand the msg right another plugin already added a "calendar" button to the header.
This plugin does not need any holiday plugin or ever needed a extra plugin for holidays.
