### ISSUE TITLE
Redmine 3.4.2 - ActionView::Template::Error

### ISSUE THREAD

**Issue by naguera** [berti92/mega_calendar#64]
Hi, installation ok w/o errors. Menù ok, calendar ok. 

When you submit a new issue or when you try to view an existent it gives an error:

![image](https://user-images.githubusercontent.com/30929548/29214381-69507a30-7ea7-11e7-9696-a4fa7ffd4a1c.png)

Here is log/production.log:

`Started GET "/issues/30" for 127.0.0.1 at 2017-08-11 15:14:26 +0200
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"30"}
  Current user: admin (id=1)
  Rendered issues/_action_menu.html.erb (7.6ms)
  Rendered plugins/mega_calendar/app/views/issues/show.html.erb within layouts/base (83.4ms)
Completed 500 Internal Server Error in 417ms (ActiveRecord: 39.0ms)

ActionView::Template::Error (undefined method `render_custom_fields_rows' for #<#<Class:0x007f3f04ccb010>:0x007f3f04cdb118>):
    252:     rows.right l(:label_spent_time), (@issue.total_spent_hours > 0 ? link_to(l_hours(@issue.total_spent_hours), issue_time_entries_path(@issue)) : "-"), :class => 'spent-time'
    253:   end
    254: end %>
    255: <%= render_custom_fields_rows(@issue) %>
    256: <%= call_hook(:view_issues_show_details_bottom, :issue => @issue) %>
    257: </table>
    258:
  plugins/mega_calendar/app/views/issues/show.html.erb:255:in `_plugins_mega_calendar_app_views_issues_show_html_erb__2270648528821368524_69954320124720'
  app/controllers/issues_controller.rb:106:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:99:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
`

Here is my conf (puma+nginx):

![image](https://user-images.githubusercontent.com/30929548/29214567-219838e4-7ea8-11e7-850d-eb84650cffa3.png)

Thanks

**Comment by whitehander** [comment]
I've got same errors.

**Comment by Einfach-Ich** [comment]
Hi,
Redmine has made some changes.

These changes help:

File: mega_calendar/app/views/issues/show.html.erb
row 83 and 255

```
<%= render_custom_fields_rows(@issue) %>
<%= call_hook(:view_issues_show_details_bottom, :issue => @issue) %>
</div>
```
->

```
<%= render_half_width_custom_fields_rows(@issue) %>
<%= call_hook(:view_issues_show_details_bottom, :issue => @issue) %>
</div>
```

And

row 174 and 346

`<%= context_menu issues_context_menu_path %>`

->

`<%= context_menu %>`

After these changes. It worked fine :-)

**Comment by naguera** [comment]
Thanks for your suggestion @Einfach-Ich! It seems to work with these modifications, anyway page rendering is not correct... 
![image](https://user-images.githubusercontent.com/30929548/29821776-62b15908-8cc9-11e7-8cb2-67ee7509a869.png)

**Comment by Einfach-Ich** [comment]
Oh sorry,

change the first line :-)

`<% if Redmine::VERSION.to_s.starts_with?('3.2') || Redmine::VERSION.to_s.starts_with?('3.3') %>`

->

`<% if Redmine::VERSION.to_s.starts_with?('3.2') || Redmine::VERSION.to_s.starts_with?('3.4') %>`

Now works :-)

**Comment by naguera** [comment]
@Einfach-Ich, AWESOME, thanks again.

ps. maybe you are able to fix also the related #65 :-D

**Comment by berti92** [comment]
Sorry for the late response, I was a little bit busy. Thank you all for your comments and your work.
The problem is fixed.

**Comment by qq649814002** [comment]
@berti92 Hello,I have got the same error when I used redmine in new user.Can you tell me how you solded the problem?I need your help.
