### ISSUE TITLE
Redmine 3.4.2 - Start date & Due date visualization issue

### ISSUE THREAD

**Issue by naguera** [berti92/mega_calendar#65]
After installation the mini-calendar where you can choose a start date and a due date when creating/modifying issue is not shown while time fields are. Also, you must insert date in format yyyy-mm-dd when usually I can insert in dd/mm/yyyy (IT LOCAL).

![image](https://user-images.githubusercontent.com/30929548/29215055-cd3ef1be-7ea9-11e7-9b9e-f6437fc67152.png)

Related to #64 

Thanks

**Comment by Einfach-Ich** [comment]
Hi,

the solution:

File: plugins/mega_calendar/app/views/issues/_attributes.html.erb

change the first row:

`<% if Redmine::VERSION.to_s.starts_with?('3.3') %>`
->
`<% if Redmine::VERSION.to_s.starts_with?('3.4') %>`


should be fine.

best regards

**Comment by berti92** [comment]
Sorry for the late response, I was a little bit busy. Thank you all for your comments and your work.
The problem is fixed.
