### ISSUE TITLE
New Holiday is not getting added

### ISSUE THREAD

**Issue by GruLab** [berti92/mega_calendar#69]
![holiday](https://user-images.githubusercontent.com/8300079/30822502-9c687c2a-a246-11e7-8a7c-f24ee5e42765.jpg)

1. Latest Plugin installed successfully
2. When creating new holiday, it throws error

Redmine 3.4.2 on CentOS 7

**Comment by lindhor** [comment]
Same problem with mega_calendar 1.7.0 using redmine 3.4.4 on apache httpd 2.4.6 (cantos 7.4) and ruby 2.4.2.

**Comment by berti92** [comment]
@lindhor thank you, you're right :)
