### ISSUE TITLE
Permissions 

### ISSUE THREAD

**Issue by pielat** [berti92/mega_calendar#71]
Hello,
Very nice plugin, I was looking for something with holidays in it, but calendar functionality was big surprise for me.

I've a little question about adding permissions functionality for holidays. The situation is that I can give access for regular users for managing holidays and everyone can delete someone's else holiday. I would like to have HR users with full access and regular users who can add their own holiday and view calendar with other users.

Do you think it would be hard to implement such permissions?

**Comment by 11v1** [comment]
Hello.

It was really unexpected that anyone can edit anyone's holidays.

**Comment by akhilesharora** [comment]
You can try my fork - #github.com/akhilesharora/mega_calendar.git which only allows you to change your own holidays but not anyone's else  ;)

**Comment by berti92** [comment]
Closed, because no time to enhance this plug any further.
