### ISSUE TITLE
No Issue History update after Start date/Due date change

### ISSUE THREAD

**Issue by 11v1** [berti92/mega_calendar#73]
Hi.

Issue Start date/Due date change doesn't makes any entries in Issue History log.

**Comment by flashliao** [comment]
Same Issue! Please close change after Start date/Due date functions.

**Comment by flashliao** [comment]
You can easily manage your issues or holidays. Just drag and drop them to the right date. Please canceld or add Issue History

**Comment by berti92** [comment]
Closed, because no time to enhance this plug any further.
