### ISSUE TITLE
How  to change the translation the calendar?

### ISSUE THREAD

**Issue by flashliao** [berti92/mega_calendar#75]
calendar is english translation.I'm chinaese.I try to change fullclander lang file,but did not work out.

**Comment by flashliao** [comment]
Seem just zh lang(not zh-tw) not work out!!

**Comment by flashliao** [comment]
![_2018-06-29t09-19-59 014z](https://user-images.githubusercontent.com/28710685/42084596-b134e770-7bc0-11e8-8bfa-dcfcc618b01a.png)
![_2018-06-29t09-20-40 987z](https://user-images.githubusercontent.com/28710685/42084633-ca4d62c8-7bc0-11e8-86d5-00ca74313b32.png)

**Comment by berti92** [comment]
Closed, because no time to enhance this plug any further.
