### ISSUE TITLE
Not working in futur version of Redmine 4.x

### ISSUE THREAD

**Issue by abrochet** [berti92/mega_calendar#79]
Hello,

The plugin is not compatible with the new version of Redmine 4.0 Rails 5.2 :(
The method "alias_method_chain" is missing in the new version of Rails 5.x
Obviously, it must be replaced by the method "prepend" but I do not know Ruby enough for that...

Is it possible to correct?

**Comment by berti92** [comment]
Thank you for your feedback. Tbh I didn't tested it for Redmine 4 for now, I will have a look at it in the next time.

**Comment by berti92** [comment]
Sorry for the dumb question, but how do I get V4 ?

**Comment by abrochet** [comment]
It is not officially released yet I used the version on the trunk.
Thanks for helping.

**Comment by berti92** [comment]
Should be fixed in this branch https://github.com/berti92/mega_calendar/tree/rails_4_and_5.
The branch will be merge into master if the version is released.

**Comment by abrochet** [comment]
Thank you verry much!

**Comment by Wajalot** [comment]
It's not working in 4.x version, :-(

**Comment by berti92** [comment]
@Wajalot Did you tried it with the rails_4_and_5 branch?
