### ISSUE TITLE
mega_calendar does not respect access rights to projects

### ISSUE THREAD

**Issue by lopezio** [berti92/mega_calendar#86]
I can see issues from projects where I am not involved and for which I do not have any access rights! This is a major issue... 

Edit: If there is some way of using a more abstract method from redmine to list/filter out the issues, maybe that would be a better way to go. This would also solve #85... (I haven't looked up the internals enough, but I suppose there should be some methods in the core bundle that could also be usable by plug-ins, without necessarily resorting to the REST API..?)

**Comment by berti92** [comment]
Closed, because no time to enhance this plug any further.
