### ISSUE TITLE
Filters barely usable on Safari (macOS) and too unspecific generally

### ISSUE THREAD

**Issue by lopezio** [berti92/mega_calendar#87]
Filters are difficult to use because the multi-select box is a one-liner on macOS / Safari (see screenshot). 

Also, they do not conform to the rest of redmine. I think You should use the same mechanism used throughout redmine (instead of just "contains" "does not contain").

![image](https://user-images.githubusercontent.com/1156208/53011320-6b0bd680-3440-11e9-9f34-b37062d09229.png)

**Comment by slim-benhammouda** [comment]
any visibility on this issue?
redmine 4.2.5
chrome 102

Many thanks
