### ISSUE TITLE
support webcal

### ISSUE THREAD

**Issue by gorsing** [berti92/mega_calendar#94]
Support for the webcal standard will help integrate into many many third-party applications, for example, for the nextcloud-calendar application nextcloud-desk.

**Comment by berti92** [comment]
This is possible with the upcoming version. Here the URL to get the .ics by a fixed link.

<REDMINE_URL>/<MegaCalendar SubPath>/calendar/export?time_start=2022-01-01&time_end=2022-12-31&key=<YOUR_API_KEY>

Please change the time_start and time_end value to a small date range to decrease the load on the server.
