### ISSUE TITLE
Q: Howto create link to specific calendar view?

### ISSUE THREAD

**Issue by albrechtd** [berti92/mega_calendar#97]
A *really* nice plugin!

As a (hopefully not too dumb) request for the FAQ's: I would like to hack the `:top_menu` to add a link to a specific mega calendar view.  I.e. if the user clicks the link, the `calendar` url should be opened, but with a few pre-set items, e.g. “all tickets”, “week view”, and “filter id 3”.

Would this be possible?  How?

**Comment by berti92** [comment]
Hi @albrechtd,

thank you for your interest in one folder and sorry for my late response. As always with free projects, there is not much time to support them or write new features.

You could archive that really easy, just add a new line to the init.rb of this project right below https://github.com/berti92/mega_calendar/blob/8c7386a45a504473d3ad442aa8f32d78bbb6f4ec/init.rb#L15. Just copy that line and enter your desired location

I hope I helped you!

Best regards Berti
