### ISSUE TITLE
Groups missing in mega calendar

### ISSUE THREAD

**Issue by jackryan172** [berti92/mega_calendar#98]
In megacalendar, the Assignee list contains only individual users no groups.  When an event is assigned a group, it will not display in Mega Calendar. 
it does not contain any of the groups. It's a little odd that the Assignee list in Megacalendar uses the login name,  This is different than "FirstName LastName" everywhere else in Redmine.

**Comment by jackryan172** [comment]
Here is what I was talking about:

![Megacalendar_Assignee_Field_Edited](https://user-images.githubusercontent.com/12191544/113433140-a3669880-93ac-11eb-8bbe-caaa0b606780.png)



another Image:
![Normal_Assignee_Field_Edited](https://user-images.githubusercontent.com/12191544/113433143-a3ff2f00-93ac-11eb-949c-21b7bc731b9b.png)

**Comment by berti92** [comment]
Oh yes, you're right. I never implemented groups, because I didn't used them. I mark this issue as bug.
